force-app/main/default/objects/Customer_Portfolio_Summary__c/Customer_Portfolio_Summary__c.object-meta.xml
<CustomObject>
    <label>Customer Portfolio Summary</label>
    <nameField>
        <label>Customer Portfolio Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Portfolio Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Energy_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Energy_Percentage__c</fullName>
    <label>Energy Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Financials_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Financials_Percentage__c</fullName>
    <label>Financials Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/FMCG_Percentage__c.field-meta.xml
<CustomField>
    <fullName>FMCG_Percentage__c</fullName>
    <label>FMCG Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Healthcare_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Percentage__c</fullName>
    <label>Healthcare Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Industrials_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Industrials_Percentage__c</fullName>
    <label>Industrials Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Materials_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Materials_Percentage__c</fullName>
    <label>Materials Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Technology_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Technology_Percentage__c</fullName>
    <label>Technology Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Telecom_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Telecom_Percentage__c</fullName>
    <label>Telecom Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Total_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Total_Portfolio__c</fullName>
    <label>Total Portfolio</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Portfolio_Summary__c/fields/Utilities_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Utilities_Percentage__c</fullName>
    <label>Utilities Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/Market_Event__c.object-meta.xml
<CustomObject>
    <label>Market Event</label>
    <nameField>
        <label>Market Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Event__c/fields/Event_Processed_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Processed_Time__c</fullName>
    <label>Event Processed Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/High_Count__c.field-meta.xml
<CustomField>
    <fullName>High_Count__c</fullName>
    <label>High Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/Impact_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Impact_Percentage__c</fullName>
    <label>Impact Percentage</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/Impact_Score__c.field-meta.xml
<CustomField>
    <fullName>Impact_Score__c</fullName>
    <label>Impact Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Pharma</fullName>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>FMCG</fullName>
            </value>
            <value>
                <fullName>Steel/Metals</fullName>
            </value>
            <value>
                <fullName>Cement</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Conglomerate</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/Low_Count__c.field-meta.xml
<CustomField>
    <fullName>Low_Count__c</fullName>
    <label>Low Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/Medium_Count__c.field-meta.xml
<CustomField>
    <fullName>Medium_Count__c</fullName>
    <label>Medium Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/News_Suggestion__c.field-meta.xml
<CustomField>
    <fullName>News_Suggestion__c</fullName>
    <label>News Suggestion</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/News_Summary__c.field-meta.xml
<CustomField>
    <fullName>News_Summary__c</fullName>
    <label>News Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/News_Title__c.field-meta.xml
<CustomField>
    <fullName>News_Title__c</fullName>
    <label>News Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market_Event__c/fields/Sentiment__c.field-meta.xml
<CustomField>
    <fullName>Sentiment__c</fullName>
    <label>Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarketEventNewsController.cls
public with sharing class MarketEventNewsController {

    @AuraEnabled(cacheable=true)
    public static Market_Event__c getLatestNegativeEvent() {
        return [
            SELECT Id, Name, News_Title__c, News_Summary__c, News_Suggestion__c, Industry__c,High_Count__c, Medium_Count__c, Low_Count__c,Impact_Score__c,Impact_Percentage__c
            FROM Market_Event__c
            WHERE Sentiment__c = 'Negative'
            ORDER BY Event_Processed_Time__c DESC
            LIMIT 1
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Customer_Portfolio_Summary__c> getImpactedCustomers(String level, String industry) {

        String fieldName = getFieldByIndustry(industry);
        if(String.isBlank(fieldName) || String.isBlank(level)){
            return new List<Customer_Portfolio_Summary__c>();
        }

        String condition = '';

        if(level == 'High'){
            condition = fieldName + ' > 30';
        } 
        else if(level == 'Medium'){
            condition = fieldName + ' >= 20 AND ' + fieldName + ' <= 30';
        } 
        else if(level == 'Low'){
            condition = fieldName + ' < 20';
        }
        String query = 'SELECT Id, Customer_Name__c, Total_Portfolio__c, ' + fieldName +
                       ' FROM Customer_Portfolio_Summary__c ' +
                       'WHERE ' + fieldName + ' != NULL AND ' + condition +
                       ' ORDER BY ' + fieldName + ' DESC LIMIT 200';

        return Database.query(query);
    }
    private static String getFieldByIndustry(String industry) {

        if(industry == null) return null;

        industry = industry.toLowerCase().trim();
        if(industry.contains('it') || industry.contains('tech') || industry.contains('technology'))
            return 'Technology_Percentage__c';

        if(industry.contains('bank') || industry.contains('financial'))
            return 'Financials_Percentage__c';

        if(industry.contains('pharma') || industry.contains('health'))
            return 'Healthcare_Percentage__c';

        if(industry.contains('fmcg'))
            return 'FMCG_Percentage__c';

        if(industry.contains('energy'))
            return 'Energy_Percentage__c';

        if(industry.contains('telecom'))
            return 'Telecom_Percentage__c';

        if(industry.contains('industrial'))
            return 'Industrials_Percentage__c';

        if(industry.contains('material'))
            return 'Materials_Percentage__c';

        if(industry.contains('utility'))
            return 'Utilities_Percentage__c';

        return null;
    }

@AuraEnabled
public static void notifyCustomer(Id customerId) {
    System.debug('Notify customer: ' + customerId);
}
@AuraEnabled
public static Id findAccountByName(String customerName) {

    if(String.isBlank(customerName)) return null;

    List<Account> acc = [
        SELECT Id
        FROM Account
        WHERE Name LIKE :('%' + customerName + '%')
        LIMIT 1
    ];

    return acc.isEmpty() ? null : acc[0].Id;
}
@AuraEnabled
public static void runEmailFlow(String recordId) {

    if (String.isBlank(recordId)) {
        throw new AuraHandledException('RecordId is missing');
    }

    try {
        Map<String, Object> inputs = new Map<String, Object>{
            'recordId' => recordId
        };

        Flow.Interview.Market_Email_Notify flow =
            new Flow.Interview.Market_Email_Notify(inputs);

        flow.start();

    } catch (Exception e) {
        throw new AuraHandledException('Flow execution failed: ' + e.getMessage());
    }
}
@AuraEnabled
public static void runWhatsAppFlow(String recordId) {

    if (String.isBlank(recordId)) {
        throw new AuraHandledException('RecordId is missing');
    }

    try {
        Map<String, Object> inputs = new Map<String, Object>{
            'recordId' => recordId
        };

        Flow.Interview.Whatsapp_Message_Notify flow =
            new Flow.Interview.Whatsapp_Message_Notify(inputs);

        flow.start();

    } catch (Exception e) {
        throw new AuraHandledException('WhatsApp Flow failed: ' + e.getMessage());
    }
}
}